name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the terminal output and screenshots/sample media (if applicable).

  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: terminal_output
    attributes:
      label: Terminal output
      description: Paste the terminal output or error traceback here.
      render: shell

  - type: textarea
    id: media
    attributes:
      label: Screenshots and sample media
      description: Drag and drop screenshots or problematic images/videos here.
